[package]
name = "cw-ibc-lite-types"
description = "Shared types for IBC Lite in CosmWasm"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
ibc-core-host = { workspace = true }
ibc-client-cw = { workspace = true }
cw-ownable = { workspace = true }
