[package]
name = "cw-ibc-lite-derive"
description = "This crate contains macros for deriving cw-ibc-lite interfaces."
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[lib]
doctest = false
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
